name: Python application

on: 
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        ./manage.sh test --noinput --failfast

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Run ansible playbook
      run: |
        cd ansible
        ansible-galaxy install cchurch.uwsgi
        ansible-galaxy install geerlingguy.certbot
        ansible-galaxy install geerlingguy.nginx
        echo '${{ secrets.VAULT_PASS }}' > vault-pass.txt
        ansible-vault decrypt id_rsa_horodeya.pem.encrypted --vault-password-file=vault-pass.txt
        ansible-playbook -i production playbook.yaml --private-key=id_rsa_horodeya.pem.encrypted --vault-password-file=vault-pass.txt
