name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        cd ansible
        ansible-vault decrypt id_rsa_horodeya.pem.encrypted --vault-password='${{ secrets.VAULT_PASS }}'
        ansible-playbook -i production playbook.yaml --private-key=id_rsa_horodeya.pem.encrypted --vault-password='${{ secrets.VAULT_PASS }}'
