name: Test

on: 
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Test
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py test --noinput --failfast

